### PR TITLE
CPP-5241 Migrate github action from build-wrapper-output to compilation-database

### PR DESCRIPTION
**Pull request by enzo-pellegrini**
List of checkpoint to verify/do before merging a PR.

### Dev checklist

* [ ] Write/update tests
* [ ] Functional validation
* [ ] Public documentation update
* [ ] Private documentation update
* [ ] Clean commits (should start with a ticket number, clear message, no fixup, wip)
* [ ] Maximize code coverage as much as possible

---

### Reviewer checklist

* [ ] Code review
* [ ] Functional validation
* [ ] Check commits are clean

---

### Steps to validate this PR

Fill-in how you performed the validation, and how the reviewer can replicate it:
* [ ]

### CODE REVIEW

**Review by michael-jabbour-sonarsource — APPROVED** [review]
LGTM from my side. Could you also amend the commit to include the ticket number?

I think that we can merge this PR now as the new version of the analyzer is now live on SC.

**Review by antoine-vinot-sonarsource — APPROVED** [review]
LGTM. 
The PR is still in a Draft state. We usually mark it as ready for review before assigning reviewers.

**Comment by michael-jabbour-sonarsource** [comment]
Thanks for pointing that out @antoine-vinot-sonarsource. Do you think we can go ahead and proceed with the merge now?

**Comment by antoine-vinot-sonarsource** [comment]
> Thanks for pointing that out @antoine-vinot-sonarsource. Do you think we can go ahead and proceed with the merge now?

Yes sure, I approved it already.

**Pull request merged**
