### PR TITLE
SCCPPGHA-2 Support macOS ARM runners

### PR DESCRIPTION
**Pull request by enzo-pellegrini**
List of checkpoint to verify/do before merging a PR.

### Dev checklist

* [x] Write/update tests
* [ ] Functional validation
* [ ] Public documentation update
* [ ] Private documentation update
* [x] Clean commits (should start with a ticket number, clear message, no fixup, wip)
* [ ] Maximize code coverage as much as possible

---

### Reviewer checklist

* [ ] Code review
* [ ] Functional validation
* [ ] Check commits are clean

---

### Steps to validate this PR

Fill-in how you performed the validation, and how the reviewer can replicate it:
* [ ]

### CODE REVIEW

**Review by michael-jabbour-sonarsource — COMMENTED** [review]
LGTM from my side! Could you check the dev checklist and make sure that all items are checked before we go ahead and ask for a review from AE? Especially the one regarding commit messages.

**Comment by enzo-pellegrini** [comment]
> Especially the one regarding commit messages.
You think they mean I should have both commits start with the ticket number which is in the title of the PR?

**Review by antoine-vinot-sonarsource — CHANGES_REQUESTED** [review]
Please don't forget to squash the commits and have it start with the ticket number

**Comment by enzo-pellegrini** [comment]
Hi, I have squashed the commits, and also did so for the other PR https://github.com/SonarSource/sonarqube-github-c-cpp/pull/8 , let me know if there are any other changes I should make.

**Review by antoine-vinot-sonarsource — APPROVED** [review]
LGTM!

**Comment by enzo-pellegrini** [comment]
@antoine-vinot-sonarsource I have merged this pr, what is your (AE) process for the status jira ticket? (same for the SQ pr)
Also as a side note, do you usually do the release of the action after such updates? Right now the changes are not in the latest release and therefore not available by users (or by repos in https://github.com/sonarsource-cfamily-examples)

**Comment by antoine-vinot-sonarsource** [comment]
Hey @enzo-pellegrini, sorry for the late answer!

> I have merged this pr, what is your (AE) process for the status jira ticket? (same for the SQ pr)

We usually close the ticket once the PR is merged.

> Also as a side note, do you usually do the release of the action after such updates? Right now the changes are not in the latest release and therefore not available by users (or by repos in https://github.com/sonarsource-cfamily-examples)

We don't have a well-defined process for releasing those repositories at the moment. Thus, my guess is that we will release it anytime we think it makes sense.

**Pull request merged**
